version: "3.9"
services:
  # Python
  web:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    links:
      - db
    #networks: app-network

  #MySQL
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    #networks: app-network

#Network
#networks:
  #app-network:
    #driver: bridge